filter:
  paths: [api/config/*, api/module/*]
  # excluded_paths: [vendor/*, test/*]
before_commands:
  - 'composer install --dev --prefer-source'
checks:
  php:
    code_rating: true
    duplication: true
tools:
  external_code_coverage:
    runs: 2
    timeout: 600
  php_code_coverage: true
  php_code_sniffer: true
  php_cpd:
    enabled: true
    # excluded_dirs: [vendor, test]
  php_cs_fixer:
    enabled: true
    config: { level: psr2 }
  php_loc:
    enabled: true
    # excluded_dirs: [vendor, test]
  php_mess_detector: true
  php_pdepend: true
  sensiolabs_security_checker: true
