language: php

matrix:
    include:
        - php: 5.6
          env:
            - EXECUTE_COVERAGE=true
        - php: 7
        - php: hhvm
    allow_failures:
        - php: 7
        - php: hhvm

before_script:
    - cd api
    - composer self-update
    - composer install --no-interaction --ignore-platform-reqs --prefer-source

# install:
#     - composer install --no-interaction --ignore-platform-reqs --prefer-source

script:
    ls module/Channel/test
    phpunit -c module/Channel/test/phpunit.xml
